//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_PAGE
    {
        public int PAGE_ID { get; set; }
        public string PAGE_URL { get; set; }
        public int ACTOR_ID_P { get; set; }
    
        public virtual S_ACTORS S_ACTORS { get; set; }
    }
}
